{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: fintech
spec:
  partitions: {{ .partitions | default 1 }}
  replicas: {{ .replicas | default 1 }}
  {{- if .config }}
  config:
    {{- toYaml .config | nindent 4 }}
  {{- end }}
{{- end }}
