{{- $appsetName := .Values.appsetName }}
{{- $project := .Values.project }}
{{- $repoURL := .Values.template.source.repoURL }}
{{- $targetRevision := .Values.template.source.targetRevision }}
{{- $path := .Values.template.source.path }}
{{- $destServer := .Values.template.destination.server }}
{{- $destNamespace := .Values.template.destination.namespace }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $appsetName }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    {{- toYaml .Values.generators | nindent 4 }}
  template:
    metadata:
      name: '{{ $appsetName }}-{{ "{{service}}" }}'
    spec:
      project: {{ $project }}
      source:
        repoURL: {{ $repoURL }}
        targetRevision: {{ $targetRevision }}
        path: charts/base-service
        helm:
          releaseName: '{{ "{{service}}" }}'
          valueFiles:
          - '../../fintech/services/{{ "{{service}}" }}/values.yaml'
      destination:
        server: {{ $destServer }}
        namespace: {{ $destNamespace }}
      syncPolicy:
        {{- toYaml .Values.syncPolicy | nindent 8 }}
