apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appsetName }}
  namespace: {{ .Values.namespace }}
spec:
  generators:
    {{- toYaml .Values.generators | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.appsetName }}-{{ "{{ service }}" }}
    spec:
      project: {{ .Values.project }}
      source:
        repoURL: {{ .Values.template.source.repoURL }}
        targetRevision: {{ .Values.template.source.targetRevision }}
        path: {{ .Values.template.source.path }}
      destination:
        server: {{ .Values.template.destination.server }}
        namespace: {{ .Values.template.destination.namespace }}
      syncPolicy:
        {{- toYaml .Values.syncPolicy | nindent 8 }}
